### ISSUE TITLE
 How do you control the duration of the animation?

### ISSUE THREAD

**Issue by ggg66** [athn-nik/motionfix#1]
Great work! looking for your reply!

**Comment by atnikos** [comment]
Hello @ggg66 and thanks for the interest in our work :)
You can do so here[here](https://github.com/athn-nik/motionfix/blob/c22df23f3dfad286d47d5db63ebdac5f81dac31b/motionfix_evaluate.py#L211), by controlling the length of the target animations.
However, since most of our pairs are of same length, I do not expect to get good results, for now.
