### ISSUE TITLE
Unnormalized Translation of the First Frame

### ISSUE THREAD

**Issue by lzhyu** [athn-nik/motionfix#3]
Hi,
Thanks for the great work. I came across a minor detail in the implementation that I couldn’t quite understand:
https://github.com/athn-nik/motionfix/blob/67e1195050666a3ad55bcd19b438322330348663/src/model/base_diffusion.py#L782

From my understanding, the translation of the first frame is always zero. Should it be unnormalized in this line?

**Comment by atnikos** [comment]
Hello,
yes it is set to zero. This is a design choice (all motions are set to start from zero translation in train, val and test sets). This is to make the motion edits interpretable (all motions should start from the same point and orientation and then "be different").

During inference, since we are predicting deltas (roughly trans[i]-trans[i-1]), we choose to have the initial translation set to zero for fair comparisons and to make the edits visible (i.e., both source and target motion start from the same point in space).

**Comment by lzhyu** [comment]
Hi,
Thanks for the explanation. However, I observed that when I printed the SMPL vector produced by `motionfix_evaluate.py`
```motion_path = r"PATH/TO/NPY"
motion = np.load(motion_path, allow_pickle=True).item()['pose']
print(motion[:1, :3])
```

The translation of the first frame is 
`[4.23084013e-02, -4.18675467e-02, -1.15762670e-2]` rather than zero.  Am I misunderstanding something?

**Comment by atnikos** [comment]
Hello, you are right. Let me fix my previous response they all start roughly from `(0,0,0)`.
The slight difference is caused from [this line](https://github.com/atnikos/motionfix/blob/67e1195050666a3ad55bcd19b438322330348663/src/model/base_diffusion.py#L782).
 This makes it start from:` 'mean': array([ 0.0423084 , -0.04186755, -0.01157627] `, which is the mean translation of all motions.
